raw_inputs:
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam/train.csv"

inputs:
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam-splitted/more_questions_raw_questions_wiki_sci_1_train.csv"
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam-splitted/more_questions_raw_questions_wiki_sci_1_test.csv"

load_from: "microsoft/deberta-v3-large"

report_to: ["wandb"]
lr: 2e-6
use_peft: False
peft_class: "AdaLoraConfig"
use_8bit: False
gradient_accumulation_steps: 128
total_epochs: 20
add_context: True
early_stopping_patience: 100000000
save_total_limit: 10
peft_lr: 5e-6
eval_on: "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam/train.csv"
eval_all_folds: True
# fold:
#   num: 0
#   of: 10