inputs:
  - "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/reproduce-mgoksu-deotte/train_data_final/train_data_final.csv"
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/cdeotte-60k-data-with-context-v2/all_12_with_context2_FIXED.csv"
  

load_from:  "microsoft/deberta-v3-large" # "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128/deberta-v3-large-2023-08-30-13-15-21/checkpoint-1143"

report_to: ["wandb"]
lr: 2e-6
use_peft: False
peft_class: "AdaLoraConfig"
use_8bit: False
gradient_accumulation_steps: 32
max_context_size: 450
total_epochs: 40
early_stopping_patience: 10
peft_lr: 5e-6
eval_on: 
  - "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/reproduce-mgoksu-deotte/test_data/train_context_0.csv"
eval_all_folds: True
save_total_limit: 10
# fold:
#   num: 0
#   of: 10
