inputs:
  # - "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/reproduce-mgoksu-deotte/test_data/train_context_0.csv"
  - "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/reproduce-mgoksu-deotte/train_data_1_and_2_final/train_data_final.csv"
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/cdeotte-60k-data-with-context-v2/all_12_with_context2.csv"
  # - "/home/viktor/Documents/kaggle/kaggle_llm/data/cdeotte-40k/MMLU_17k_with_context2.csv"
  # - "/home/viktor/Documents/kaggle/kaggle_llm/data/cdeotte-40k/OpenBook_with_context2.csv"
  # - "/home/viktor/Documents/kaggle/kaggle_llm/data/cdeotte-40k/ScienceQA_with_context2.csv"

load_from: "/home/viktor/Documents/kaggle/kaggle_llm/data/llama2-7b-stem" # "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128/deberta-v3-large-2023-08-30-13-15-21/checkpoint-1143"

report_to: ["wandb"]
lr: 2e-6
use_8bit: True
gradient_accumulation_steps: 32
separate_prompt_and_context: False
preprocess_type: "deotte"
max_input: 300
warmup_epochs: 0
total_epochs: 300
early_stopping_patience: 10
use_peft: False
peft_class: "AdaLoraConfig"
peft_lr: 2e-6
peft_kwargs:
  r: 1024
  lora_alpha: 256
  lora_dropout: 0.1
  target_modules: ["q_proj", "v_proj"]


eval_on: 
  - "/home/viktor/Documents/kaggle/kaggle_llm/work_dirs/reproduce-mgoksu-deotte/test_data/train_context_0.csv"
  # - "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam/train.csv"
eval_all_folds: True
save_total_limit: 10
# fold:
#   num: 0
#   of: 10
