raw_inputs:
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam/train.csv"

inputs:
  - "/home/viktor/Documents/kaggle/kaggle_llm/data/kaggle-llm-science-exam/train.csv"

load_from: "microsoft/deberta-v3-large"

report_to: ["wandb"]
lr: 5e-6
use_peft: False
peft_class: "AdaLoraConfig"
use_8bit: False
gradient_accumulation_steps: 16
total_epochs: 100
early_stopping_patience: 100000000000
peft_lr: 5e-6
fold:
  num: 0
  of: 10