inputs:
  - "/home/clay/research/kaggle/kaggle_llm/data/additional-train-data-for-llm-science-exam/extra_train_set.csv"
  - "/home/clay/research/kaggle/kaggle_llm/data/kaggle-llm-science-exam-splitted/train.csv"

#load_from: "/home/clay/research/kaggle/kaggle_llm/data/pretrained_models/google-electra-base-discriminator"
load_from: "/home/clay/research/kaggle/kaggle_llm/data/deberta-v3-large-notebook-weights"
