models:
  - "deberta-v3-data-mix-1-eval-kaggle-all-folds-grad-accum-128-ACTUAL/deberta-v3-large-2023-08-29-10-26-03/checkpoint-1738"



configs:
  - "deberta-v3-data-mix-1-eval-kaggle-all-folds-grad-accum-128-ACTUAL/configs"


use_peft: False
use_8bit: False
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"