models:
  - "google-electra-base-discriminator-2023-07-23-21-46-32/checkpoint-500"
#  - "google-electra-base-discriminator-2023-07-23-21-46-32/checkpoint-1000"
#  - "google-electra-base-discriminator-2023-07-23-21-46-32/checkpoint-1500"
#  - "google-electra-base-discriminator-2023-07-23-21-46-32/checkpoint-2000"
