models:
  - "deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128-30k/deberta-v3-large-2023-09-04-23-24-56/checkpoint-1640"



configs:
  - "deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128-30k/configs"


use_peft: False
use_8bit: False
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"