models:
  - "160k-viktor-and-deotte-dataset-deotte-preproc-deberta-context-12/peft-checkpoint-14450-2023-09-26-00-09-57/checkpoint-50"

configs:
  - "160k-viktor-and-deotte-dataset-deotte-preproc-deberta-context-12/configs"


use_peft: False
use_8bit: True
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"

separate_prompt_and_context: False