models:
  - "deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128/deberta-v3-large-2023-08-30-13-15-21/checkpoint-1224"



configs:
  - "deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128/configs"


use_peft: False
use_8bit: False
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"