models:
  - "deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128-60k-viktor-dataset-deotte-preproc/deberta-v3-large-2023-09-10-00-56-02/checkpoint-22500"

configs:
  - "deberta-v3-data-wiki_sci-with-wiki-sentence-context-eval-kaggle-all-folds-grad-accum-128-60k-viktor-dataset-deotte-preproc/configs"


use_peft: False
use_8bit: True
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"

separate_prompt_and_context: True