models:
  - "deberta-v3-large-on-raw_questions_wiki_sci_1-eval-kaggle-all-folds-grad-accum-16/deberta-v3-large-2023-08-24-14-33-06/checkpoint-3592"


configs:
  - "deberta-v3-large-on-raw_questions_wiki_sci_1-eval-kaggle-all-folds-grad-accum-16/config"



use_peft: False
use_8bit: False
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"