models:
  - "deberta-v3-data-mix-1-eval-kaggle-all-folds-grad-accum-128/deberta-v3-large-2023-08-27-16-12-06/checkpoint-1738"


configs:
  - "deberta-v3-data-mix-1-eval-kaggle-all-folds-grad-accum-128/configs"


use_peft: False
use_8bit: False
tokenization: "get_tokenize_dataset_from_df"
data_collator: "DataCollatorForMultipleChoice"